name: mtp
n_embd: 768
n_component: 5
n_token: 3

lm: &lm_encoder
    _target_: nanogpt.models.gpt.GPTEncoder
    config:
      _target_: nanogpt.utils.Config
      vocab_size: ${data.vocab_size}
      n_embd: ${model.n_embd}
      n_layer: 12
      n_head: 6
head: &lm_head
    _target_: nanogpt.models.circuit.MultiTokenHead
    vocab_size: ${data.vocab_size}
    n_embd: ${model.n_embd}
    n_component: ${model.n_component}
    n_token: ${model.n_token}
circuit: &circuit
    _target_: nanogpt.models.circuit.CircuitCP
    vocab_size: ${data.vocab_size}
    n_token: ${model.n_token}
    n_component: ${model.n_component}
model:
    _target_: nanogpt.models.mt.MultiTokenLM
    lm_encoder: *lm_encoder
    lm_head: *lm_head
    circuit: *circuit
