vocab_size: 50304
n_embd: 768
n_head: 6
n_component: 1
n_token: 4

gpt: &gpt
    _target_: nanogpt.models.gpt.GPT
    vocab_size: ${model.vocab_size}
    n_embd: ${model.n_embd}
    n_head: ${model.n_head}
    n_layer: 12
mt_head: &mt_head
    _target_: nanogpt.models.circuit.MultiTokenHead
    vocab_size: ${model.vocab_size}
    n_embd: ${model.n_embd}
    n_head: ${model.n_head}
    n_component: ${model.n_component}
    n_token: ${model.n_token}
circuit: &circuit
    _target_: nanogpt.models.circuit.CircuitCP
    vocab_size: ${model.vocab_size}
    n_token: ${model.n_token}
    n_component: ${model.n_component}
model:
    _target_: nanogpt.models.mt.MultiTokenLM
    gpt: *gpt
    mt_head: *mt_head
    circuit: *circuit
