name: lora-last-2

# See https://github.com/ctlllll/axolotl/blob/main/examples/medusa/vicuna_13b_qlora_stage1.yml
hyperparameters:
  r: 16
  lora_alpha: 16
  lora_dropout: 0.
  target_modules:
    - gate_proj
    - down_proj
    - up_proj
    - q_proj
    - v_proj
    - k_proj
    - o_proj
  layers_to_transform: ${lm.last_2_layers}
