name: evabyte
n_embd: 4096
n_head: 32

model:
    _target_: mtp.models.lm.LM
    lm: null
    encoder_only: true
    from_checkpoint: null
    from_huggingface: evabyte/EvaByte
    adaptor_kwargs: ${adaptor.hyperparameters}
    ref_enc: model
    ref_head: lm_head
    freeze: true
