apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: s2457990-infk8s-mtp-pvc
  labels:
    eidf/user: s2457990-infk8s
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Gi
  storageClassName: csi-rbd-sc
