name: mtp
n_embd: 768
n_head: 6
n_component: 1
n_token: 4

lm: &lm
    _target_: mtp.models.lm.LM
    # lm:
    #     _target_: mtp.models.gpt.GPT
    #     vocab_size: ${data.vocab_size}
    #     n_embd: ${model.n_embd}
    #     n_head: ${model.n_head}
    #     n_layer: 12
    encoder_only: true
    from_checkpoint: null
    ref_enc: encoder
    ref_head: head
    freeze: true
mt_head:
    _target_: mtp.models.mtp_head.MultiTokenHead
    vocab_size: ${data.vocab_size}
    n_embd: ${model.n_embd}
    n_head: ${model.n_head}
    n_layer: 2
    n_component: ${model.n_component}
    n_token: ${model.n_token}
circuit:
    _target_: mtp.models.circuits.CircuitCP
    vocab_size: ${data.vocab_size}
    n_token: ${model.n_token}
    n_component: ${model.n_component}
model:
    _target_: mtp.models.mtp.MultiTokenLM
    lm: ${model.lm}
    mt_head: ${model.mt_head}
    circuit: ${model.circuit}
