defaults:
  - _self_
  - training: default
  - model: default
  - generate: default
  - data: shakespeare_char

name: nanogpt
compile: true
ddp: true
device: cuda   # can be cpu only if ddp is False
# checkpoint: logs/2025-01-16/15-59-39/model@250.pth
checkpoint: null

hydra:
  job:
    chdir: true
    name: ${name}
    env_set:
      OMP_NUM_THREADS: 1
      CUDA_VISIBLE_DEVICES: 0,1,2
  run:
    dir: ./logs/${now:%Y-%m-%d}/${now:%H-%M-%S} 

  job_logging:
    formatters:
      simple:
        format: '[%(asctime)s] - %(message)s'
