defaults:
  - _self_
  - training: default
  - model: default

name: nanogpt
compile: true
device: cpu

data:
  train_bin: '/home/grv/Playground/multi-token/nanoGPT/fineweb10B/fineweb_train_*.bin'
  val_bin: '/home/grv/Playground/multi-token/nanoGPT/fineweb10B/fineweb_val_*.bin'

hydra:
  job:
    chdir: true
    name: ${name}
    env_set:
      OMP_NUM_THREADS: 1
      CUDA_VISIBLE_DEVICES: 0
  run:
    dir: ./logs/${now:%Y-%m-%d}/${now:%H-%M-%S} 

  job_logging:
    formatters:
      simple:
        format: '[%(asctime)s] - %(message)s'
