defaults:
  - _self_
  - training: default
  - model: gpt
  - data: shakespeare_char
  - generate: default

name: nanogpt
compile: true
device: cuda   # if cpu make source num processes=1
# from_checkpoint: logs/2025-01-16/15-59-39/model@250.pth
from_checkpoint: null

hydra:
  job:
    chdir: true
    name: ${name}
  run:
    dir: ./logs/${now:%Y-%m-%d}/${now:%H-%M-%S} 

  job_logging:
    formatters:
      simple:
        format: '[%(asctime)s] - %(message)s'
