#!/bin/bash

export MTP_ROOT=`pwd`
export GPUS=2
export CUDA_VISIBLE_DEVICES=0,1
export WANDB_MODE=disabled
export OMP_NUM_THREADS=1
export CUBLAS_WORKSPACE_CONFIG=:4096:8
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
export NCCL_NET_GDR_LEVEL=2
export NCCL_IB_DISABLE=0
export CUDA_LAUNCH_BLOCKING=0
python ./scripts/deepspeed_runner_nanoGPT_adapt.py --num_gpus=2 --module mtp.deepspeed_train \
    data=finewebedu10B \
    training=finewebedu \
    lm=finewebedu \
    model=basharin \
    model.n_token=4 \
    model.n_component=2 \
    model.model.gamma=1 \
    model.model.kl_algorithm=binary_approx \
    model.model.beta=.9 \
    lm.model.encoder_only=false \
    model.mt_head_hparams.sum_transformer_n_layer=0 \
    model.mt_head_hparams.tok_transformer_n_layer=0 \
    model.mt_head_hparams.expander_type=linear \
    lm.model.freeze=true \
    model.mt_head_hparams.freeze_vocab_unembedding=true \
    training.device_batch_size=4 \
    training.expname=basharin-akl+ce-n-4-r-4-deepspeed-debug \
    training.save_model_every=5 \
    from_checkpoint=$MTP_ROOT/logs/2025-04-05/02-08-32/5