name: random-btree
n_token: 4      # Any number > 1
n_component: 2  # Any number > 1
n_repetition: 3  # Any number > 0

model:
    _target_: mtp.models.circuits.CircuitModel
    vocab_size: ${data.vocab_size}
    n_token: ${circuit.n_token}
    n_component: ${circuit.n_component}
    n_repetition: ${circuit.n_repetition}
    kind: 'random-btree'

